routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//menu
Route::get('/menu', 'MenuController@index')->name('menu');
Route::get('/menu/{slug}', 'MenuController@show')->name('menu.slug');
Route::get('/single', 'IndexController@single');

Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'IndexController@index')->name('index');
Route::get('/contact', 'IndexController@contact');

//CART
Route::get('/cart', 'CartController@index');
Route::delete('/cart/remove/{id}', 'CartController@destroy')->name('cart.destroy');
Route::post('/cart/{id_product}/{id_user}', 'CartController@store')->name('cart.store');
Route::post('/cart/update', 'CartController@update');

//checkout
Route::get('/checkout/{id}', 'CheckoutController@index');
Route::get('/province', 'CheckoutController@get_province');
Route::get('/kota/{id}', 'CheckoutController@get_city');
Route::get('/origin={city_origin}&destination={city_destination}&weight={weight}&courier={courier}', 'CheckoutController@get_ongkir');
Route::post('/checkout/{id}', 'CheckoutController@store')->name('checkout.store');

//User
Route::get('/user/{id}', 'UserController@index');
Route::put('/user/{id}', 'UserController@update');

//transaksi
Route::get('transaksi', 'TransaksiController@index');
Route::get('transaksi/{id_transaksi}', 'TransaksiController@detail');
Route::put('transaksi/{id_transaksi}', 'TransaksiController@update');
Route::put('/transaksi/{id_transaksi}/{user_id}', 'TransaksiController@selesai');

//Admin
Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {
    Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

    Route::resource("examples", "Admin\AdminController");

    Route::resource("transactions", "Admin\TransactionController");
});

//SuperAdmin
Route::resource("super-admin", "Admin\SuperAdminController")->middleware(['super']);

resources/views/backend/partials/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

resources/views/backend/partials/head.blade.php
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{$title}}</title>

    <link rel="shortcut icon" href="{{ asset('images/icon.ico') }}">
    <!-- Custom fonts for this template-->
    <link href="{{asset('vendor/backend')}}/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <!-- Custom styles for this template-->
    <link href="{{asset('vendor/backend')}}/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Datatables -->
    <link href=" {{ asset('vendor/backend') }}/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href=" {{ asset('vendor/backend') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">


    <style>
        /* Chrome, Safari, Edge, Opera */
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        /* Firefox */
        input[type=number] {
            -moz-appearance: textfield;
        }
    </style>
    <style>
        .image-popup {
            cursor: -webkit-zoom-in;
            cursor: -moz-zoom-in;
            cursor: zoom-in;
        }
    </style>

</head>

resources/views/backend/partials/modal.blade.php
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{{ route('logout') }}" onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">Logout</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/backend/partials/navbar.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>


    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                            aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">{{ $notifcount }}</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Notifikasi Bukti Pembayaran
                </h6>

                @if(!@empty($notif))
                @foreach ($notif as $item)
                <a class="dropdown-item d-flex align-items-center"
                    href="{{ route('admin.transactions.show',$item->id_transaksi) }}">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">{{ $item->updated_at}}</div>
                        {{ $item->id_transaksi}}
                    </div>
                </a>
                @endforeach
                @endif
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }} </span>
                <img class="img-profile rounded-circle" src="{{asset('images/foto.jpg')}}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="" data-toggle="modal" data-target="#logoutModal"><i
                        class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    {{ __(' Logout') }}
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

resources/views/backend/partials/scripts.blade.php
<!-- Bootstrap core JavaScript-->
<script src="{{asset('vendor/backend')}}/vendor/jquery/jquery.min.js"></script>
<script src="{{asset('vendor/backend')}}/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="{{asset('vendor/backend')}}/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="{{asset('vendor/backend')}}/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="{{asset('vendor/backend')}}/vendor/chart.js/Chart.min.js"></script>

<!-- Page level custom scripts -->
<script src="{{asset('vendor/backend')}}/js/demo/chart-area-demo.js"></script>
<script src="{{asset('vendor/backend')}}/js/demo/chart-pie-demo.js"></script>

<script src="{{asset('vendor')}}/sweetalert/sweetalert.all.js"></script>
<script src="{{asset('vendor')}}/sweetalert/myscript.js"></script>

<script src="{{ asset('vendor/backend') }}/vendor/datatables/jquery.dataTables.js"></script>
<script src="{{ asset('vendor/backend') }}/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('vendor/backend') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>


<script>
    $(document).ready(function() {
    $('#example').DataTable();
} );
</script>

<script type="text/javascript">
    $(function() {
        $('.btn-danger').click(function() {
            id = $(this).attr('data-id');
            $('#input-id').val(id);
            
            // alert( $('#input-id').val() )
        });
    });
</script>


@include('sweetalert::alert')
@yield('pageScripts')

resources/views/backend/partials/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('admin') }}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Edi Jaya Beef <sup>Admin</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {{$active == "dashboard" ? "active" : ""}}">
        <a class="nav-link" href="{{ url('admin') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Super Admin
    </div>


    <!-- Nav Item - Contoh -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('super-admin.index') }}">
            <i class="fas fa-fw fa-user"></i>
            <span>Super Admin</span></a>
    </li>

    <!-- Heading -->
    <div class="sidebar-heading">
        Admin
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
            aria-controls="collapseTwo">
            <i class="fab fa-product-hunt"></i>
            <span>Produk</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">List Produk:</h6>
                <a class="collapse-item" href="{{route('admin.examples.index')}}">Produk</a>
                <a class="collapse-item" href="{{route('admin.examples.create')}}">Tambah Produk</a>
            </div>
        </div>
    </li>


    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        User
    </div>


    <!-- Nav Item - Contoh -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.transactions.index') }}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Transaksi</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->