routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//menu
Route::get('/menu', 'MenuController@index')->name('menu');
Route::get('/menu/{slug}', 'MenuController@show')->name('menu.slug');
Route::get('/single', 'IndexController@single');

Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'IndexController@index')->name('index');
Route::get('/contact', 'IndexController@contact');

//CART
Route::get('/cart', 'CartController@index');
Route::delete('/cart/remove/{id}', 'CartController@destroy')->name('cart.destroy');
Route::post('/cart/{id_product}/{id_user}', 'CartController@store')->name('cart.store');
Route::post('/cart/update', 'CartController@update');

//checkout
Route::get('/checkout/{id}', 'CheckoutController@index');
Route::get('/province', 'CheckoutController@get_province');
Route::get('/kota/{id}', 'CheckoutController@get_city');
Route::get('/origin={city_origin}&destination={city_destination}&weight={weight}&courier={courier}', 'CheckoutController@get_ongkir');
Route::post('/checkout/{id}', 'CheckoutController@store')->name('checkout.store');

//User
Route::get('/user/{id}', 'UserController@index');
Route::put('/user/{id}', 'UserController@update');

//transaksi
Route::get('transaksi', 'TransaksiController@index');
Route::get('transaksi/{id_transaksi}', 'TransaksiController@detail');
Route::put('transaksi/{id_transaksi}', 'TransaksiController@update');
Route::put('/transaksi/{id_transaksi}/{user_id}', 'TransaksiController@selesai');

//Admin
Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {
    Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

    Route::resource("examples", "Admin\AdminController");

    Route::resource("transactions", "Admin\TransactionController");
});

//SuperAdmin
Route::resource("super-admin", "Admin\SuperAdminController")->middleware(['super']);

resources/views/backend/examples/create.blade.php
@extends('backend.master')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Produk</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.examples.index') }}">Produk</a></li>
                <li class="breadcrumb-item active" aria-current="page">Tambah</li>
            </ol>
        </nav>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Form Tambah Product</h6>
                </div>
                <div class="card-body">
                    <form enctype="multipart/form-data" class="form-horizontal"
                        action="{{route('admin.examples.store')}}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="input_text">Nama Produk</label>
                                <input type="text" class="form-control" id="product_name" name="product_name"
                                    placeholder="ex : tenderloin">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="harga_produk">Harga Produk</label>
                                <input type="number" class="form-control" id="product_price" name="product_price"
                                    placeholder="ex : 50000">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="input_select">Kategori</label>
                                <select class="form-control" id="category" name="category">
                                    <option value="dg_sapi">Daging Sapi</option>
                                    <option value="dg_kambing">Daging Kambing</option>
                                    <option value="buntut">Buntut</option>
                                    <option value="lainnya">Lainnya</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="stok">Stok</label>
                                <input type="number" class="form-control" id="stok" name="stok" placeholder="ex : 50">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_textarea">Deskripsi</label>
                                <textarea class="form-control" id="description" name="description" rows="3"></textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_file">Masukkan Gambar</label><br>
                                <div class="input-group mb-3 col-md-12">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="input_picture"
                                            name="input_picture">
                                        <label class="custom-file-label" for="input_picture">Pilih Gambar</label>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary col-12">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

resources/views/backend/examples/detail_transaksi.blade.php
@extends('backend.master')

@section('content')
<div class="container bootstrap snippet">
    <div class="row">
        <div class="col-md-12 ftco-animate">
            <a href="{{ route('admin.transactions.index') }}" class="btn btn-primary">Kembali</a>
            <h3 class="mb-4 billing-heading">Detail Transaksi</h3>
            <p>Kode Transaksi : {{ $transactions->id_transaksi }}</p>
            @php
            $no = 1;
            @endphp
            <div class="cart-list">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Produk</th>
                            <th>Banyak Produk</th>
                            <th>Harga</th>
                            <th>Jumlah Harga</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($detailtransactions as $item)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $item->product_name }}</td>
                            <td>{{ $item->qty }} Kg</td>
                            <td>{{ $item->product_price }}</td>
                            <td>Rp.{{number_format( $item->jumlah_harga,0,",",".") }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="4" align="right" style="color:#c49b63">
                                Total Harga :
                            </td>
                            <td><strong style="color:#c49b63">Rp.{{number_format($item->total,0,",",".")}}</strong>
                            </td>
                        </tr>
                    </tfoot>
                </table>
                <a href="{{ route('admin.transactions.edit',$item->id_transaksi) }} "
                    class="btn btn-primary mb-5 col-lg-12">Ubah
                    Status</a>
            </div>
        </div>
        <div class="col-lg-6 mb-5 ftco-animate">
            <div class="card" style="width: 18rem">
                @if($transactions->bukti)
                <a href="{{asset('uploads/bukti/'.$transactions->bukti)}}" class="image-popup"><img
                        src="{{asset('uploads/bukti/'.$transactions->bukti)}}" class="card-img-top"
                        alt="Card image cap"></a>
                @endif

            </div>
        </div>
        <div class="col-lg-6 mb-5 ftco-animate">
            <div class="card">
                <div class="card-body">
                    <p>{{ $transactions->address }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/backend/examples/edit.blade.php
@extends('backend.master')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Ubah Produk</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{route('admin.examples.index')}}">Example</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ubah</li>
            </ol>
        </nav>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Form Ubah Product</h6>
                </div>
                <div class="card-body">
                    <form enctype="multipart/form-data" class="form-horizontal"
                        action="{{route('admin.examples.update',$item->id)}}" method="POST">
                        @method('put')
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="input_text">Nama Produk</label>
                                <input type="text" class="form-control" id="product_name" name="product_name"
                                    placeholder="ex : tenderloin" value="{{ $item->product_name }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="input_number">Harga Produk</label>
                                <input type="number" class="form-control" id="product_price" name="product_price"
                                    placeholder="ex : 50000" value="{{ $item->product_price }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="input_select">Kategori</label>
                                <select class="form-control" id="category" name="category">
                                    <option value="dg_sapi">Daging Sapi</option>
                                    <option value="dg_kambing">Daging Kambing</option>
                                    <option value="buntut">Buntut</option>
                                    <option value="lainnya">Lainnya</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="stok">Stok</label>
                                <input type="number" class="form-control" id="stok" name="stok" placeholder="ex : 50"
                                    value="{{ $item->stok }}">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_textarea">Deskripsi</label>
                                <textarea class="form-control" id="description" name="description"
                                    rows="3">{{ $item->description }}</textarea>
                            </div>
                            <div class="form-group col-md-6">
                                <input type="hidden" class="form-control" id="slug" name="slug" placeholder="slug"
                                    value="{{ $item->slug }}">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_picture">Masukkan Gambar</label><br>
                                <div class="input-group mb-3 col-md-12">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="input_picture"
                                            name="input_picture">
                                        <label class="custom-file-label" for="input_picture">Pilih Gambar</label>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary col-12">Ubah</button>
                            <a href="{{ route('admin.examples.index') }}"
                                class="btn btn-danger col-12 mt-1">Batalkan</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

resources/views/backend/examples/edit_transactions.blade.php
@extends('backend.master')

@section('content')
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Ubah Status Transaksi</h6>
            <p>Kode Transaksi : {{ $transactions->id_transaksi }}</p>
        </div>
        <div class="card-body">
            <form action="{{ route('admin.transactions.update',$transactions->id_transaksi) }}" method="POST">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="status">Status Transaksi</label>
                    <select name="status" required-class="form-control">
                        <option value="{{ $transactions->status }}">Ini Statusnya -> {{ $transactions->status }}
                        </option>
                        <option value="belum bayar">Belum Bayar</option>
                        <option value="berhasil upload">Berhasil Upload</option>
                        <option value="pembayaran terkonfirmasi">Pembayaran Terkonfirmasi</option>
                        <option value="sedang di proses">Sedang di Proses</option>
                        <option value="sedang di kirim">Sedang di Kirim</option>
                        <option value="selesai">Selesai</option>
                        <option value="cancel">Cancel</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary btn-block">Ubah</button>
                <a href="{{route('admin.transactions.index')}}" class="btn btn-danger btn-block">Kembali</a>
            </form>
        </div>
    </div>
</div>
@stop

resources/views/backend/examples/index.blade.php
@extends('backend.master')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Produk </h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Produk</li>
                <li class="breadcrumb-item active"><a href="{{route('admin.examples.create')}}">Tambah</a></li>
            </ol>
        </nav>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Produk</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="example" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Produk</th>
                            <th>Kategori</th>
                            <th>Harga Produk</th>
                            <th>Stok</th>
                            <th>Deskripsi</th>
                            <th>Foto</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($products as $item)
                        <tr>
                            <td>{{$item->product_name}}</td>
                            <td>{{$item->category}}</td>
                            <td>{{$item->product_price}}</td>
                            <td>{{$item->stok }}</td>
                            <td>{{$item->description}}</td>
                            <td>
                                @if ($item->input_picture)
                                <img src="{{ asset('uploads/product/' . $item->input_picture) }}" class="img-fluid"
                                    alt="" width="30%">
                                @endif
                            </td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <div class="col-md-6 mt-2">

                                        <a href="{{ route('admin.examples.edit',$item->id) }}"
                                            class="btn btn-primary fas fa-edit pr-1" style="color: aliceblue">Ubah</a>

                                    </div>
                                    <div class="col-md-6 mt-2">
                                        <button class="btn btn-danger" data-toggle="modal" data-id="{{ $item->id }}"
                                            data-target="#deleteModal">
                                            <i class="fa fa-trash pr-1">Hapus</i>
                                        </button>
                                    </div>

                                    <!-- Delete Modal-->
                                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Hapus Produk</h5>
                                                    <button class="close" type="button" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">Apakah anda yakin ingin menghapusnya?</div>
                                                <div class="modal-footer">
                                                    <button class="btn btn-secondary" type="button"
                                                        data-dismiss="modal">Batal</button>
                                                    <form action="{{ route('admin.examples.destroy',$item->id) }}"
                                                        method="POST" class="delete">
                                                        @csrf
                                                        @method('delete')
                                                        <input type="hidden" name="id" id="input-id">
                                                        <button class="btn btn-primary btn-delete">Hapus</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

resources/views/backend/examples/transactions.blade.php
@extends('backend.master')

@section('content')
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Transaksi</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="example" width="100%" cellspacing="0">
                    @php
                    $no = 1;
                    @endphp
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Id Transaksi</th>
                            <th>Nama Pembeli</th>
                            <th>Status</th>
                            <th>Total</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($transactions as $item)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $item->id_transaksi }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->status }}</td>
                            <td>{{ $item->total }}</td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <div class="col-md-6 mt-2">
                                        <a href="{{ route('admin.transactions.edit',$item->id_transaksi) }}"
                                            class="btn btn-primary"><i class="fa fa-pencil-square-o"
                                                aria-hidden="true"></i>Ubah</a>
                                    </div>
                                    <div class="col-md-6 mt-2">
                                        <a href="{{ route('admin.transactions.show',$item->id_transaksi) }}"
                                            class="btn btn-secondary">Detail</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop