routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//menu
Route::get('/menu', 'MenuController@index')->name('menu');
Route::get('/menu/{slug}', 'MenuController@show')->name('menu.slug');
Route::get('/single', 'IndexController@single');

Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'IndexController@index')->name('index');
Route::get('/contact', 'IndexController@contact');

//CART
Route::get('/cart', 'CartController@index');
Route::delete('/cart/remove/{id}', 'CartController@destroy')->name('cart.destroy');
Route::post('/cart/{id_product}/{id_user}', 'CartController@store')->name('cart.store');
Route::post('/cart/update', 'CartController@update');

//checkout
Route::get('/checkout/{id}', 'CheckoutController@index');
Route::get('/province', 'CheckoutController@get_province');
Route::get('/kota/{id}', 'CheckoutController@get_city');
Route::get('/origin={city_origin}&destination={city_destination}&weight={weight}&courier={courier}', 'CheckoutController@get_ongkir');
Route::post('/checkout/{id}', 'CheckoutController@store')->name('checkout.store');

//User
Route::get('/user/{id}', 'UserController@index');
Route::put('/user/{id}', 'UserController@update');

//transaksi
Route::get('transaksi', 'TransaksiController@index');
Route::get('transaksi/{id_transaksi}', 'TransaksiController@detail');
Route::put('transaksi/{id_transaksi}', 'TransaksiController@update');
Route::put('/transaksi/{id_transaksi}/{user_id}', 'TransaksiController@selesai');

//Admin
Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {
    Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

    Route::resource("examples", "Admin\AdminController");

    Route::resource("transactions", "Admin\TransactionController");
});

//SuperAdmin
Route::resource("super-admin", "Admin\SuperAdminController")->middleware(['super']);

app/Http/Controllers/Admin/SuperAdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Transaction;
use App\User;
use RealRashid\SweetAlert\Facades\Alert;

class SuperAdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['title'] = 'Daftar User';
        $data['active'] = 'produk';
        $data['notifcount'] = Transaction::where([
            'status' => 'berhasil upload'
        ])->count();
        $data['users'] = User::all();
        return view('backend.superadmin.index', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title'] = 'Ubah Roles';
        $data['active'] = 'superadmin';
        $data['notifcount'] = Transaction::where([
            'status' => 'berhasil upload'
        ])->count();
        $item = User::findOrFail($id);
        return view(
            'backend.superadmin.edit',
            [
                'item' => $item
            ],
            $data
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        User::where('id', $id)
            ->update([
                'roles' => $request->roles,
            ]);

        Alert::success('Sukses !', 'Roles Berhasil diubah.');
        return redirect()->route('super-admin.index');
    }
}

resources/views/backend/superadmin/edit.blade.php
@extends('backend.master')

@section('content')
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Ubah Roles User</h6>
        </div>
        <div class="card-body">
            <form action="{{ route('super-admin.update',$item->id) }}" method="POST">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="name">Nama User :</label>
                    <span><strong>{{ $item->name }}</strong></span>
                </div>
                <div class="form-group">
                    <label for="roles">Roles User</label>
                    <select name="roles" required-class="form-control">
                        <option value="">-- Ini Rolesnya -> {{ $item->roles }} --
                        </option>
                        <option value="SUPER">Super Admin</option>
                        <option value="ADMIN">Admin</option>
                        <option value="USER">User</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary btn-block">Ubah</button>
                <a href="{{ route('super-admin.index') }}" class="btn btn-danger btn-block">Kembali</a>
            </form>
        </div>
    </div>
</div>
@stop

resources/views/backend/superadmin/index.blade.php
@extends('backend.master')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Users </h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Super Admin</li>
            </ol>
        </nav>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables User</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="example" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nama User</th>
                            <th>Email</th>
                            <th>Roles</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $item)
                        <tr>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->email }}</td>
                            <td>{{ $item->roles }}</td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <div class="col-md-6 mt-2">
                                        <a href="{{ route('super-admin.edit',$item->id) }}"
                                            class="btn btn-primary fas fa-edit pr-1" style="color: aliceblue">Ubah</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection